Replaced echo for printf where safer/compliant

diff --git a/.bin/map-path b/.bin/map-path
--- a/.bin/map-path
+++ b/.bin/map-path
@@ -2,11 +2,9 @@
 # github.com/fl0at/dotfiles
 # run a command (or ls, if not specified) recursively on directory components
 
-# TODO: use printf instead of echo, to use --? Is it portable?
-
 if [ -z "$*" ]
 then
-	echo -e "usage: $0 path [[cmd] [arg1] ...]\n\nbreak apart and recursively call directory portions of a path, running [cmd] or 'ls -lad' if unspecified"; exit 64 #EX_USAGE
+	printf "usage: $0 path [[cmd] [arg1] ...]\n\nbreak apart and recursively call directory portions of a path, running [cmd] or 'ls -lhd' if unspecified"; exit 64 # exit status 64 is EX_USAGE
 fi
 
 TREE=`readlink -f $1`
